CREATE DATABASE `demo` /*!40100 COLLATE 'utf8_general_ci' */

CREATE USER 'demo'@'%' IDENTIFIED BY 'demo';

GRANT USAGE ON *.* TO 'demo'@'%';

//GRANT ALL ON demo.* TO 'demo'@'%' WITH GRANT OPTION;

GRANT	SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE,
		CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE,
		DROP, EVENT, INDEX, INSERT, REFERENCES,
		TRIGGER, UPDATE, LOCK TABLES  ON `demo`.* TO 'demo'@'%' WITH GRANT OPTION;
		
FLUSH PRIVILEGES;